name: 'isaac_analytics'
version: '1.0.0'
config-version: 2

# Profile reference matching profiles.yml definitions
profile: 'isaac_analytics'

# dbt virtual directory routing
model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages", "logs"]

# Global configurations applied across all sub-directory models
models:
  isaac_analytics:
    gold:
      +materialized: table
      +format: parquet
      +write_compression: snappy
